### ISSUE TITLE
Evaluating Bug: "labeled icon menu" meet "fluid menu" and "text menu"

### ISSUE THREAD

**Issue by faller** [Semantic-Org/Semantic-UI#1540]
http://jsfiddle.net/3uzh6t1d/6/

text menu has an extra margin-left and right 

label icon menu should not has min-width when fluid

**Comment by jlukic** [comment]
Confirmed

**Comment by jlukic** [comment]
Fixed in d3b3ea387facaa6bed132ffcd8b1b713cbec81e9 in `1.6.0`

**Comment by faller** [comment]
@jlukic still have problem, text menu has an extra margin-left and right when fluid
http://jsfiddle.net/3uzh6t1d/8/

**Comment by jlukic** [comment]
This appears to affect ``ui fluid text menu`` only (it uses negative margins to remove padding on first item).

Fixed in next
http://jsfiddle.net/3yaz465o/
