### ISSUE TITLE
Accordion revealing hidden content while opening

### ISSUE THREAD

**Issue by mikocot** [Semantic-Org/Semantic-UI#1551]
Hi,

I was surprised by a weird behavior of my website after migrating to 1.x (currently 1.4)

Apparently, elements hidden with display: none, are made visible again anytime an accordion is opened.

See here for example:
http://jsfiddle.net/uk4a4cej/5/

I was able to find that there is a reset.display method called on each element, resetting display to "".
"Removing inline display from element".

Pretty irritating, especially together with knockout that uses inline display for visible binding.

Cheers

**Comment by jlukic** [comment]
Caused by typo. Should only clear inline opacity styles. See 7166d51

**Comment by mikocot** [comment]
Haha, seems reasonable. that was a quick response. Thanks :)

**Comment by mikocot** [comment]
Hi again, we are using 1.7.3 in production, which has this patch already working.

However, in some cases the accordion still removes display:none inline style from some elements inside.
(ex. ui label with knockout validationMessage gets revealed.)

I've checked that turning settings.animateChildren to false solves the problem. So basicallyt this part is responsible:

```$activeContent
                  .children()
                    .transition({
                      animation  : 'fade in',
                      useFailSafe : true,
                      debug      : settings.debug,
                      verbose    : settings.verbose,
                      duration   : settings.duration
                    });                

any ideas?

**Comment by xover424** [comment]
Was this ever resolved as of the latest version? I'm having similar issues with it "unhiding" hidden elements.

**Comment by jlukic** [comment]
I dont really understand this issue

**Comment by xGouley** [comment]
Still happening!

Every element (div, span at least) in a accordion receives the following class by semantic in JS way, during opening:
.visible.transition {
    display: block!important;
    visibility: visible!important;
}

Too much aggressive from Semantic, but there is a way to bypass behavior: encapsulate the div you want to hide by another div. Since .visible.transition is applied only on the first level of div, you can hide the sub-div.

**Comment by RobinKuiper** [comment]
@xGouley Thank you for this fix. Was trying everything.

**Comment by labby** [comment]
@xGouley: also a big thank from me, also tried several solutions.

**Comment by martin-bailey** [comment]
This seems to be causing issues in Semantic-UI 2.13 depending on how your CSS is bundled.

`.ui.accordion .title~.content{display:none}`

Should it be the following?

`.ui.accordion .title~.content:not(.active){display:none}`
