### ISSUE TITLE
Window doesnt scroll when modal is larger than viewport

### ISSUE THREAD

**Issue by ghost** [Semantic-Org/Semantic-UI#165]
Can not scroll to content that has overflowed. If there is a lot of modal content, the actions are pushed off the bottom of the viewport.

Tested on Mac OSX 10.8.5 Chrome, Canary, FF, Opera, Safari

**Comment by stanzakh** [comment]
In case anybody else has this issue and stumbles upon this thread, I was able to get it to work by calling refresh on the modal in the `onVisible` callback:

    $("#your-modal")
    .modal({
        onVisible: function () {
            $("#your-modal").modal("refresh");
        }
    })
    .modal("show");

**Comment by jlukic** [comment]
I'm considering moving the modal to flexbox to make vertical centering not require javascript. If anyone wants to experiment with this its available in branch `flex`.

**Comment by gdw2** [comment]
I'm using meteor's autoform which has dynamically expanding content.  Refreshing the modal works until the content is larger than the window itself, at which point, the portion of the content that is off-screen is inaccessible.

**Comment by jlukic** [comment]
@gdw2 Have you tried using [`observeChanges`](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/modal.js#L824) or `.modal('refresh')`

**Comment by gdw2** [comment]
I've tried `.modal('refresh')`.  I need to investigate more because the demo in the semantic-ui docs scrolls just fine.

**Comment by MohammedThaer** [comment]
I tried all the solutions that mentioned above and the problem still there, I don't know should I create a new issue or this comment is enough.

I have a modal and I get its content via ajax after showing the modal, the content is bigger than the view port and I cant scroll .

Please what should I do?

**Comment by jlukic** [comment]
Create a reproducible test case by forking jsfiddle in readme.

**Comment by MohammedThaer** [comment]
@jlukic Thank you for quick reply, actually I forgot to tell something maybe it cause the issue.
I've prefixed the Semantic UI css (semantic.min.css) with my custom class (using less) like the following:

`.Tajer {
  @import (less) url("semantic.min.css");
}`

All the Semantic UI elements and modules goes inside a div have that class.

Everything worked perfectly and I reached to the end of my project but unfortunately this issue appeared.

My modal settings like the following:

`$('.ui.modal').modal({
    onShow:UserProducts.getModalContent,
    context:$("div.Tajer"),
    transition: 'horizontal flip'
});`

Thank you in advance for your help. Keep up the good work!

**Comment by jlukic** [comment]
Hi thanks for the kind words. For me to debug I need a standalone reproducible test case. If you need help getting this together I recommend our Project Talk or Gitter for support.

**Comment by MohammedThaer** [comment]
Thank you. I'll try Project Talk and Gitter and if I could't find a solution I'll create a reproducible test case and update you here.

**Comment by MohammedThaer** [comment]
@jlukic I do it!
First of all I want to thank you so much, your quick replies pushed me to find a solution, I touched how Semantic UI have a good author and how I can rely on this library.

Now for anyone have a similar issue and need to know the solution, here is what I've made.

Because I prefixed the library with my custom class I should not target that class in the `context` modal settings option, I should target another class within that class, now my modal settings like the following:

`$('.ui.modal').modal({
                onShow: UserProducts.getModalContent,
                observeChanges: true,
                context: $("div.tajer-content"),
                transition: 'horizontal flip'
            });`

This "div.tajer-content" selector is a div inside "div.Tajer".

**Comment by jlukic** [comment]
Thanks @MohammedThaer. Glad you found an answer to your issue.

**Comment by kumar67** [comment]
Jack, 
Thank you so much for this awesome framework! God bless you & your family.

I'm still stumped with the missing scrollbar when using any "ui modal". I was wondering if you have any pointers how to proceed.

Thanks,

**Comment by wanchopeblanco** [comment]
I was just having this same problem with content larger than the screen, the modal appears larger than the screen and when scrolling the modal wont scroll but the background (page content) will scroll.

I started playing with the CSS and found that changing to this in the, but when getting to the bottom of the modal it will start scrolling the page content. But at least it scrolls the modal.

Still i dont undestand the issue.

```css
.scrolling.undetached.dimmable.dimmed > .dimmer {
    overflow: scroll !important;
}
```

By the way, thanks for the great work on this framework.

**Comment by avalanche1** [comment]
`observeChanges` helped

**Comment by wanchopeblanco** [comment]
I tryed observeChanges and refresh but it wouldnt help.

**Comment by avalanche1** [comment]
make a fiddle and we'll try to figure it out

**Comment by wanchopeblanco** [comment]
I couldnt reproduce the error on fiddle, when doing it on meteorpad i did but it was fixed by aplying observeChanges:true, finally i just added this to my CSS.

```css
.scrolling.undetached.dimmable.dimmed > .dimmer {
    overflow: scroll !important;
}

.scrolling.undetached.dimmable.dimmed{
    overflow: hidden !important;
}
```

If i can reproduce the problem in the next days i will post it here, thanks.

**Comment by avalanche1** [comment]
If it doesnt reproduce on fiddle, you should narrow it down in ur project

**Comment by jlukic** [comment]
If you are using meteor you may want to be using `detachable: false`

**Comment by avalanche1** [comment]
I use Meteor as well and it works just fine :smile:

**Comment by MaZZly** [comment]
Had similar problems with a modal window containing tabs..

One of the tabs was longer and went out of viewport (esp on tablets) and was not scrollable..
The refresh worked without problems by doing:

```javascript
$('#modal a[data-tab]').on('click', function () {
            $('#modal').modal('refresh');
        });
```

Just wanted to say if someone has modal and tab problem with scrolling..

**Comment by nilsi** [comment]
Adding ``observeChanges: true`` to the modal settings solved the problem I had in my Meteor app.

**Comment by nilsi** [comment]
If I just drag in Chrome corners to make window height smaller it works on every try. Any ideas how to solve this?

**Comment by avalanche1** [comment]
make a jsfiddle or codepen and we'll give it a look

**Comment by tripflex** [comment]
The `observeChanges` did not work for me, and using the `click` method I had to click twice to get it to work correctly.

My solution since I was using tabs, was just to defer calling refresh until the tab was visible:

```js
$( '#my_tabs .item' ).tab({
	onVisible: function( tabPath ){
		console.log( 'Tab visible: ', tabPath );
		$( '#my_modal' ).modal( 'refresh' );
	}
});
```

**Comment by diuzzoli** [comment]
I thing the best way to solve this problem is to set the modal with observeChanges in true.  By default is in false.

Template.YourTemplate.onRendered(function () {
    $('.ui.modal.yourmodal').modal('observeChanges', true);
});

**Comment by vinn1** [comment]
I think I fixed this with a simple little one-liner. All you have to do is : 

 
      $('#yourdiv').on('click',function(){
        $('.modal').modal('setting', { detachable:false }).modal('show').addClass('scrolling active');
        $('body').addClass('scrolling');
      }); 


By hard-coding the 'scrolling' class in the body , it seems to work as I observed that BOTH the modal div and the body acquire a class of '.active.visible.scrolling' when you initiate the modal. But by default, the body does not acquire the 'scrolling' class unless the window is resized.  Adding that one line seems to solve that issue for me ! 

Let me know if this worked for anybody else and if this seems like the right way to go !

**Comment by vinn1** [comment]
I think I fixed this with a simple little one-liner. All you have to do is : 

 
      $('#yourdiv').on('click',function(){
        $('.modal').modal('setting', { detachable:false }).modal('show').addClass('scrolling active');
        $('body').addClass('scrolling');
      }); 


By hard-coding the 'scrolling' class in the body , it seems to work as I observed that BOTH the modal div and the body acquire a class of '.active.visible.scrolling' when you initiate the modal. But by default, the body does not acquire the 'scrolling' class unless the window is resized.  Adding that one line seems to solve that issue for me ! 

Let me know if this worked for anyone else.

**Comment by batata004** [comment]
I cant believe this bug still happens and nobody cared to solve it. -> https://github.com/Semantic-Org/Semantic-UI/issues/4196

**Comment by YLgithub** [comment]
The answer of **indesignlatam** will solve it

```
.scrolling.undetached.dimmable.dimmed > .dimmer {
    overflow: scroll !important;
}

.scrolling.undetached.dimmable.dimmed{
    overflow: hidden !important;
}
```

**Comment by batata004** [comment]
Thanks! Will that be available in the official repository? If so, when? I use semantic ui in at least 300 websites and it will be freaking boring to add this code to every site.

**Comment by lomyal** [comment]
@diuzzoli 's solution solves my problem.
Thank you!
