### ISSUE TITLE
Horizontal pointing menu's indicator/arrow is not correctly aligned in chrome

### ISSUE THREAD

**Issue by kalgon** [Semantic-Org/Semantic-UI#1854]
It works in firefox though:
![semantic-ui-pointing-menu](https://cloud.githubusercontent.com/assets/145925/6324411/07a38dc8-bb3a-11e4-9457-4d708e864a7b.png)

**Comment by jlukic** [comment]
Fixed in `next`

**Comment by kalgon** [comment]
There is still a problem with the second horizontal menu: the shadow/bar under 'Home' is 1px too low in chrome.
