### ISSUE TITLE
Sortable THs have padding for the arrows even if they don't have the ascending/descending class

### ISSUE THREAD

**Issue by gonssal** [Semantic-Org/Semantic-UI#2001]
When you apply the sortable class to a table, all the THs get a right padding for the arrow, even if they don't have the ascending or descending applied (meaning the column is sorted). This makes tables look bad when the column THs are wider than the column contents and the column isn't the sorted one.

I also think the arrows should be reversed. Ascending means from smaller to bigger (from A to Z, from 0 to 9, etc...), but currently shows an arrow pointing down, which means from bigger to smaller. Viceversa with descending.

**Comment by kvetoslavnovak** [comment]
Arrows for sorting are definitely right. Try any spreadsheet software (MS Excel, Apple Numbers  or Google Sheets).

**Comment by jlukic** [comment]
Each `th` keeps additional space saved for the arrow so that when it becomes sorted it doesn't change width. 

Can you show me an example of this displaying poorly with small `td` content? I'm seeing everything looking fine.

**Comment by gonssal** [comment]
You can see it here: http://xn--marcgonzlez-r7a.com/semantic-sorted-th-screen.png

Note that both THs are center aligend. I don't use javascript for the sorting, but server side code. The right padding should only be applied when there's either the ascending or the descending class applied to the TH. 

Also, i still think the pointers should be reversed ;)

**Comment by jlukic** [comment]
Ah, specifically when it is center aligned. That I can understand.

**Comment by jlukic** [comment]
Fixed in `next` release

**Comment by gonssal** [comment]
I'm sorry to reopen, but I just pulled from Next and this issue is still happening.

If I'm not mistaken, the problem is this:
.ui.sortable.table thead th:after { ... margin: 0 0 0 .5em ... }

The margin should only be applied when the column is actually being sorted (has ascending or descending class), not always.

**Comment by jlukic** [comment]
No you are correct. Thanks for the persistence actually. I didn't notice the margin factoring into the position.

**Comment by jlukic** [comment]
Sorry about that I was 100% incorrect. Should be fixed now.
