### ISSUE TITLE
Maintain a packaged theme alongside semantic

### ISSUE THREAD

**Issue by gabro** [Semantic-Org/Semantic-UI#2101]
Hi all, I'm building a custom packaged theme for my project and I'd like to store it in the same repo where the site source code is. Here's my directory layout:

```
├── Gulpfile.js
├── dist
├── node_modules
├── package.json
├── semantic
├── semantic.json
├── src
├── theme.config
└── themes
    ├── default
    └── mytheme
```

Since whenever I update semantic with npm the `semantic/src/themes` directory gets overridden, I thought of putting the my theme (and the default one) in a `themes` directory at root level.

Then I configured my `semantic.json` as follows:

```
{
  "base": "semantic/",
  "paths": {
    "source": {
      "config": "../theme.config",
      "definitions": "src/definitions/",
      "site": "src/site/",
      "themes": "../themes"
    },
    "output": {
      "packaged": "dist/",
      "uncompressed": "dist/components/",
      "compressed": "dist/components/",
      "themes": "dist/themes/"
    },
    "clean": "dist/"
  },
  "permission": false,
  "rtl": false,
  "version": "1.11.6"
}
```

so that I could put `theme.config` and `themes` under version control and happily ignore the `semantic` folder altogether.

Unfortunately, it looks like when I build semantic (with `gulp build`), it's still using the `semantic/src/theme.config` file.

Did I get something wrong?
And in general, is there any preferred strategy for putting only my custom packaged theme under version control being able to safely update the semantic npm package?

Thank you

**Comment by jlukic** [comment]
Hi, the themes folder shouldnt be overwritten. If it is this is a bug. Are you using `npm` for update?

**Comment by gabro** [comment]
Hi and than you for the quick feedback!

What I've tried is to clone a repo with a pre-existing `semantic` directory containing only `src/themes/mytheme/` and `src/theme.config`.
After running `npm install` and the semantic installer, the `mytheme` directory is gone (git marks it as deleted) and `theme.config` is back to the default.

My goal is rather straightforward: maintain my theme in the site repo and install/update semantic on top of it (with npm install/update). I'm open to any approach, as long as `npm install` after cloning the repo will be the only necessary operation to do.

**Comment by jlukic** [comment]
I'll test this out..

**Comment by jlukic** [comment]
I've verified this is fixed from a fresh install. Will be releasing patched version today.

**Comment by gabro** [comment]
awesome, thank you for the quick fix!

**Comment by gabro** [comment]
Hi @jlukic, I just tried the last version on master (via `npm install Semantic-Org/Semantic-UI`) and I'm still facing the same issue. Steps to reproduce:

- I clone my repo, which contains a `semantic` directory with the following layout

semantic
└── src
    ├── theme.config
    └── themes
        └── mytheme

- I run `npm install`
- I perform an "Automatic" installation of Semantic (extending my current settings)

As a result, the `mytheme` folder is gone.
Here's my (shortened) git status right after

```
modified:   semantic.json
deleted:    semantic/src/themes/mytheme/collections/message.overrides
deleted:    semantic/src/themes/mytheme/collections/message.variables
...
```

Any ideas?

**Comment by jlukic** [comment]
How recently did you install. I just pushed 1.11.7 a few minutes ago

**Comment by gabro** [comment]
Yes it shows `1.11.7`. 
I tested it against master 10 minutes ago (pointing npm to the github repo directly), since it wasn't yet release on npm.

**Comment by jlukic** [comment]
Debugging locally.

**Comment by jlukic** [comment]
Oh wait i havent published `1.11.7` to npm yet. Just did now :smile:

**Comment by gabro** [comment]
I'm trying right now (`1.11.7` fresh from npm) and I still have the same issue.
The main difference from your test case and mine, is the prior existence of the `semantic` directory.

I confirmed this behavior by doing

```
mkdir -p testproject/semantic/src/themes/fake
cd testproject
npm install semantic-ui@1.11.7
cd semantic/src/themes && ls
```

(`fake` is gone now)

The idea is that my theme is in place **before** semantic is ever installed via npm so that I can ship it with the rest of the project and run a fresh `npm install` on top of it.

**Comment by jlukic** [comment]
Ohh you are talking about from the install path. Not the upgrade path.

**Comment by gabro** [comment]
Yep, exactly. Does it make sense? Or am I getting this wrong?

**Comment by gabro** [comment]
I mean, I get that when installing the themes you need to dump the whole `themes` directory into the path (since it doesn't exist yet).
I think a preserving what's inside (i.e. a merging behavior) instead of replacing it altogether would be a sensible behavior.

Or, as always, I'm open to other suggestions for shipping my theme :)

**Comment by jlukic** [comment]
I just need to release another patch. I hadn't considered modifying the behavior of install, only update.

**Comment by gabro** [comment]
Cool, thank you!
Actually,  I don't know if you noticed but testing against master gave me this error during the Semantic installation

```
Copying UI themes

fs.js:695
  return binding.stat(pathModule._makeLong(path));
                 ^
TypeError: path must be a string
    at Object.fs.statSync (fs.js:695:18)
    at Object.exports.copyDirSyncRecursive (/Users/gabro/Work/buildo/lexdoit/webtest/node_modules/semantic-ui/node_modules/wrench/lib/wrench.js:244:23)
    at /Users/gabro/Work/buildo/lexdoit/webtest/node_modules/semantic-ui/tasks/install.js:278:16
    at /Users/gabro/Work/buildo/lexdoit/webtest/node_modules/semantic-ui/node_modules/gulp-prompt/index.js:24:5
    at Object.<anonymous> (/Users/gabro/Work/buildo/lexdoit/webtest/node_modules/semantic-ui/node_modules/gulp-prompt/node_modules/inquirer/lib/inquirer.js:81:7)
    at /Users/gabro/Work/buildo/lexdoit/webtest/node_modules/semantic-ui/node_modules/gulp-prompt/node_modules/inquirer/node_modules/async/lib/async.js:232:13
    at /Users/gabro/Work/buildo/lexdoit/webtest/node_modules/semantic-ui/node_modules/gulp-prompt/node_modules/inquirer/node_modules/async/lib/async.js:142:25
    at /Users/gabro/Work/buildo/lexdoit/webtest/node_modules/semantic-ui/node_modules/gulp-prompt/nod
> node-sass@2.0.1 install /Users/gabro/Work/buildo/lexdoit/webtest/node_modules/node-sass
> node scripts/install.js
```

**Comment by jlukic** [comment]
Yeah, i'm actively working on a fix.

**Comment by gabro** [comment]
Great, I really appreciate the live support :D Thanks for the amazing work!

**Comment by gabro** [comment]
I just tested it against the last commit and it works as expected! ;)

**Comment by jlukic** [comment]
Can you test against `master` now, i think everything is ready. If everything works out I'll package up a new patch release.

**Comment by gabro** [comment]
See my previous comment, it works after testing against 2df4e8232af5c64e175ff2c0439d982ac052d134!

Thank you again very much for the prompt support!
