### ISSUE TITLE
First popup definition in demo shows extra tooltip

### ISSUE THREAD

**Issue by dandv** [Semantic-Org/Semantic-UI#2318]
At http://semantic-ui.com/modules/popup.html, mouse over the "+". The "View Source" tooltip also appears.

![popup 2 tooltips](https://cloud.githubusercontent.com/assets/33569/7877836/bd8dafac-0594-11e5-9b97-4b1d3ba1f498.gif)

**Comment by dandv** [comment]
Same for the first item at http://semantic-ui.com/modules/rating.html.

**Comment by ikourfaln** [comment]
I think the problem was fixed on SUI 2.0:
Check http://beta.semantic-ui.com/modules/popup.html

**Comment by dandv** [comment]
I still see it:

![image](https://cloud.githubusercontent.com/assets/33569/7881602/911d06be-05b9-11e5-811c-5f5bd7505cc4.png)

**Comment by jlukic** [comment]
The view source popup appears when you hover over any area of an example. This is intended because people often complained about not being able to find the view source button.

In the 1.0 docs popups were exclusive, so this would cause the demo popups to close. They are no longer exclusive by default in 2.0.

**Comment by dandv** [comment]
What I find confusing is that "View Source" appears on when hovering over the first div, but not on the next ones. In the animated GIF, it appears over "Content", but not over "Title" or "HTML".

**Comment by ikourfaln** [comment]
as @jlukic  said, check out v2.0

**Comment by jlukic** [comment]
@dandv Yes, the original intention in 1.0 docs was to only show popup on first example, because people would "get the gist". 

The whole system is a bit of a sore point, since I kind of despise the performance hit of having a popup showing during any example interaction. 

I'll see what I can do to make this less confusing.

**Comment by jlukic** [comment]
@dandv I've now cookied "View Source" popup, it will only occur if a user has never clicked the code button before. It will also never show up in the popup docs.

**Comment by dandv** [comment]
Nice, thanks!
