### ISSUE TITLE
Search Module 2.0 - onSelect() result parameter invalid value

### ISSUE THREAD

**Issue by Airforce111** [Semantic-Org/Semantic-UI#2426]
Hellos~! In reference to the Search module, under the 'next' branch.

When using the 'category' version of the Search, and trying to use onSelect()'s 'result' parameter, the returned value is NOT the user's clicked item. Is this a possible bug or expected behaviour?

The "get result(value)" behaviour also does not return the correct selected value.

```js
$('.ui.category.search').search('get result', '1');
$('.ui.category.search').search('get result', '2');
$('.ui.category.search').search('get result', '3');
... etc...
```

Sanitized sample code below...

HTML
```html
<label>Label Here</label>
<div class="ui category search">
    <div class="ui icon input">
        <input id="sample" name="sample" autocomplete="off" class="prompt" placeholder="sample" type="text" maxlength="16" value="" />
        <i class="search icon"></i>
    </div>
    <div class="results"></div>
</div>
```

EndPoint
```js
$.fn.api.settings.api = {
    'search test': '/somewhere/here/?itema={query}&itemb={query}',
};
```

JS
```js
$('.ui.category.search').search({
    apiSettings: {
        action: 'search test',
        data: 'itema=' + encodeURIComponent(1)
            + '&itemb=' + encodeURIComponent(2),
        dataType: 'json',
    },
    type: 'category',
    minCharacters: 2,
    maxResults: 7,
    cache: true,
    onSelect: function(result, response) {
        console.warn(result, 'result');
        console.warn(response, 'response');
    },
});
```

JSON Response
```json
{
  "results": {
    "cata": {
      "name": "A Accounts",
      "results": [
        {
          "title": "235-63",
          "description": "Desc A"
        },
        {
          "title": "623-23",
          "description": "Desc B"
        }
      ]
    },
    "catb": {
      "name": "B Accounts",
      "results": [
        {
          "title": "723-36",
          "description": "Desc C"
        }
      ]
    }
  }
}
```

**Comment by jlukic** [comment]
Please create a debuggable test case that verifies your issue. You can fork the JSFiddle of `next` branch from readme. 

You can specify the returned JSON using `mockResponse`

**Comment by Airforce111** [comment]
Here you go.
http://jsfiddle.net/Airforce111/g78wswow/11/

Click on all four items to see alert response. It doesn't correspond to clicked items.
Thanks for your awesome work btw! ^o^

**Comment by jlukic** [comment]
I made a huge mistake
![](http://i.giphy.com/DuWUr6ZTz5n56.gif)

**Comment by Airforce111** [comment]
Not as bad as the poor kitten, she's stuck and frozen -_-;
Thanks many~

**Comment by jlukic** [comment]
This has been fixed now. You can use your original jsfiddle as an example, which should now work.

**Comment by boukeversteegh** [comment]
This bug still exists, 2.1.10 and on this fiddle.

Please see my testcase: http://jsfiddle.net/3n85jcpp/

There are three categories, but selecting from the third category is impossible (it maps to the previous category)
