### ISSUE TITLE
[Statistic] Size inside Group Does Not Work

### ISSUE THREAD

**Issue by tristanjahier** [Semantic-Org/Semantic-UI#3116]
I have a couple of horizontal statistics in a group. I want every single statistic in it to be "tiny".
Although the "size" parameter applies correctly on independant statistics, as soon as they are grouped it does not work anymore. I think there is a bug.

Here is a JSFiddle that perfectly demonstrates the problem: http://jsfiddle.net/c2z7ve1a/

**Comment by jlukic** [comment]
Looks like an inheritance issue

**Comment by jlukic** [comment]
Fixed in `next`, also keep in mind you'll need to use `ui tiny statistic` for this to work.

**Comment by andreyvk** [comment]
Hi @jlukic ,

Very glad you're back!

This issue is still valid. Using `ui tiny statistic` under `ui statistics` container does not work at all. Please take a look at this. It would also be nice that it works not only with `tiny` but any other size of statistic.

**Comment by JoshuaKing** [comment]
@andreyvk I found the same issue, and whilst it might not be the same solution, I found this: https://github.com/Semantic-Org/Semantic-UI-React/issues/970

And confirmed that it works like I want it two - instead of:
```
<div class="ui statistics">
    <div class="ui mini statistic">
       ...
    </div>
    <div class="ui mini statistic">
       ...
    </div>
</div>
```

Try to do this:
```
<div class="ui mini statistics">
    <div class="ui statistic">
       ...
    </div>
    <div class="ui statistic">
       ...
    </div>
</div>
```

This wont help if you're wanting to mix sizes though
