### ISSUE TITLE
relative path issue

### ISSUE THREAD

**Issue by HitomiTenshi** [Semantic-Org/Semantic-UI#3903]
Commit 0c3c41038c55d9cdb9fd1a114387ae6b63ba8a40 

now expects a dot in the full path, which breaks the path of my themes. Seems to be an issue caused by that aforementioned commit.

URL now:
`http://localhost/build/css/semantic/.themes/default/assets/fonts/icons.ttf`
causes: 404 not found

URL before that commit:
`http://localhost/build/css/semantic/themes/default/assets/fonts/icons.ttf`

notice the dot before `themes`.

**Comment by jlukic** [comment]
The commit should add `.` plus a path separator, like `./` which should resolve as same folder.

**Comment by HitomiTenshi** [comment]
I'm developing on Windows 10. Maybe Windows doesn't resolve the dot? I also don't run any special theme configs, using the default at the moment.

Here's my semantic.json:

    {
      "base": "resources/assets/semantic",
      "paths": {
        "source": {
          "config": "src/theme.config",
          "definitions": "src/definitions/",
          "site": "src/site/",
          "themes": "src/themes/"
        },
        "output": {
          "packaged": "dist/",
          "uncompressed": "dist/components/",
          "compressed": "dist/components/",
          "themes": "dist/themes/"
        },
        "clean": "dist/"
      },
      "permission": false,
      "autoInstall": false,
      "rtl": false,
      "version": "2.2.0"
    }

**Comment by jlukic** [comment]
I'd like to figure this out before pushing the next version.

**Comment by HitomiTenshi** [comment]
I just set up a fresh electron project with semantic-ui. Semantic-ui is still expecting the dot before themes. Using semantic-ui from branch `next` commit af7fcf64599664aca3cbc1cd1fc8f0f2e235217b

(That commit has the `@defaultTextFocusColor is undefined` error, so `gulp build` won't work completely. See  #3975 for a fix.)

See Chrome's errors:
[error log.txt](https://github.com/Semantic-Org/Semantic-UI/files/242418/error.log.txt)

My semantic.json:
[semantic.json.txt](https://github.com/Semantic-Org/Semantic-UI/files/242423/semantic.json.txt)

My package.json:
[package.json.txt](https://github.com/Semantic-Org/Semantic-UI/files/242433/package.json.txt)

My OS: Windows 10 x64
Hope this helps.

**Comment by jlukic** [comment]
I'm not sure how to proceed, but I'm hoping to get more feedback on if this path changes causes further issues after `2.2` release.

**Comment by bali182** [comment]
I can confirm this issue (or one maybe related) is still there in 2.2. I get urls in the output css like: `src: url(".\../themes/default/assets/fonts/icons.eot");`. This completely breaks webpack builds, so I had to remove both flags and icons. Also I'm not sure if it helps but in the default theme which I'm using the global path to the font files look OK to me:

```less
@imagePath : '../../themes/default/assets/images';
@fontPath  : '../../themes/default/assets/fonts';
```

**Comment by unt1tled** [comment]
Also getting the issue here with 2.2

**Comment by HitomiTenshi** [comment]
My issue is fixed. Seems to be some issue with an old version of `gulp-cli` (or `gulp` in general).

Try uninstalling any global `gulp` / `gulp-cli` packages.
After that install the latest `gulp-cli` globally and try building semantic-ui again.

**Comment by prateekrastogi** [comment]
I am also getting the same issue on windows 10 with semantic ui 2.2.

**Comment by cjloong** [comment]
Mine is not fixed. I've tried to drill in and found that the semantic.min.css and semantic.css differs.

Minified version
```
background:url(themes/default/assets/images/flags.png)
```

Non minified version
```
url("./themes/default/assets/images/flags.png")
```
For now, I am doing a global search and replace to insert ./ into the path.
