### ISSUE TITLE
How to implement the responsive menu? 

### ISSUE THREAD

**Issue by FingersKey** [Semantic-Org/Semantic-UI#4026]

**Comment by tuxy** [comment]
There is an example of collapsible menu here > http://semantic-ui.com/examples/responsive.html

**Comment by jlukic** [comment]
Thanks @tuxy

**Comment by rtd62** [comment]
I did a pretty good workaround using [this](https://jsfiddle.net/rtd62/061ga8sc/21/﻿﻿) Fiddle.

All you have to do to get a good mobile sidebar menu is write some custom CSS and JS on top of the existing framework. However, the sidebar does not have the ability to do dropdowns and is the only caveat.

**Comment by lroellin** [comment]
@rtd62 this fiddle is not there anymore

**Comment by haoxi911** [comment]
@rtd62 do you still have access to the workaround code? if so, would you mind to share it via a gist.

**Comment by witek1902** [comment]
**Tip:**
I implemented **menu** for desktop (hide by css for mobile) and **sidebar** for mobile (hide by css for desktop).

Useful links:
https://semantic-ui.com/modules/sidebar.html
https://semantic-ui.com/collections/menu.html
https://semantic-ui.com/examples/responsive.html

**Comment by natzar** [comment]
Another solution without a sidebar.

https://github.com/natzar/semantic-ui-hamburger/blob/master/README.md

**Comment by Firegarden** [comment]
I feel not having a single responsive menu example is enough of a stumbling block that a significant portion of first time users give up on Semantic UI. I have personally not solved this menu issue but I have made some beautify blazing fast UI's with simple vue.js and semantic ui

**Comment by zholmes1** [comment]
> I feel not having a single responsive menu example is enough of a stumbling block that a significant portion of first time users give up on Semantic UI. I have personally not solved this menu issue but I have made some beautify blazing fast UI's with simple vue.js and semantic ui

I 100% agree. This is such a common feature. It baffles me that Semantic doesn't have it.

**Comment by psy0rz** [comment]
I was looking for a good framework to make an UI. If I will have to fiddle around to create a responsive menu or hamburger menu myself, i'll just look for something else instead.

**Comment by rtd62** [comment]
Updated fiddle [here](https://jsfiddle.net/rtd62/061ga8sc/)

**Comment by mrdotballard** [comment]
I know this is a little on the hack side, and smacks in the face of DRY code, but is kind of clean and simple for using only the semantic components for the responsive menu with drop down:
repeat the html altered for both the full size menu and responsive dropdown menu and add a class for each one and the following JS:

` function checkScreenWidth(x) {
   if(x.matches) {
     $(".full-screen").css("display", "none");
     $(".small-screen").css("display", "flex");
   } else {
    $(".small-screen").css("display", "none");
    $(".full-screen").css("display", "flex");
   }
 }

 var x = window.matchMedia("(max-width: 767px");
 checkScreenWidth(x);
 x.addListener(checkScreenWidth);`

**Comment by psy0rz** [comment]
Or just use Onsen UI. It has all these things correctly built in.

**Comment by mrdotballard** [comment]
Thanks, will have a look at that. 
Yeah, I'm in full agreement it's odd/frustrating semantic doesn't have this responsive functionality built it, but when you're already well into the project with it...
