### ISSUE TITLE
Single dropdown selection does not work when clicking an item and having 'select' action (version 2.2.1)

### ISSUE THREAD

**Issue by dorsha** [Semantic-Org/Semantic-UI#4183]
Installed version: 2.2.1

I have the following dropdown configuration:

```
      dropdownSelector
          .dropdown({
            fullTextSearch: true,
            preserveHTML: true,
            onChange,
            action: 'select',
            onHide: this.onHide,
            onShow: this.onShow,
            transition
          });
```

I am using the 'select' action since I don't want the current text to be changed.

Prior version 2.2.x, it works fine.
After the upgrade, the 'onChange' is not dispatched when clicking the dropdown item - but, it dispatched when moving around with the keyboard arrow keys.

I also tried to add `allowReselection: true` but it did not fix it.

Any idea?

Clicking the item is not doing anything, but moving around with the keyboard works.
![image](https://cloud.githubusercontent.com/assets/5429033/16410042/3e3cfe06-3d29-11e6-9d43-18d7c9f35a92.png)

When I remove the 'select' action it works, but it changed the selected text.

**Comment by jlukic** [comment]
Can you create a JSFiddle? There were significant dropdown changes and I want to make sure everything is fine.

**Comment by dorsha** [comment]
Yes.

**Semantic-UI 2.1.8**:
https://jsfiddle.net/3kcftobu/
Clicking on the dropdown's items works fine (you get an alert).

**Semantic-UI 2.2.1**:
https://jsfiddle.net/y2vq2u8m/
Clicking on the dropdown's items does not trigger the alert.
It works when you try to navigate with the keyboard arrows keys. (in the previous version, navigate with the keyboard keys was not triggered the onChange event)

Ignore the bad style :)

**Comment by yaowenz** [comment]
I've got the same issue on 2.2.1

**Comment by assafg** [comment]
Any updates on this issue?

**Comment by Kukkimonsuta** [comment]
The 'onChange' trigger on keyboard arrows keys seem to be intended change and you can disable it by setting new option `selectOnKeydown` to `false`. This however still doesn't change the fact, that `onChange` doesn't trigger on either `click` or `enter` when `action == 'select'`.

**Semantic-UI 2.2.1**
https://jsfiddle.net/y2vq2u8m/1/

**Comment by dorsha** [comment]
@jlukic, any update regarding this issue?
It's blocking us for upgrading to Semantic-UI 2.2.x

**Comment by jlukic** [comment]
Working on this now.

**Comment by jlukic** [comment]
I've fixed this for next patch release.

**Comment by martinduparc** [comment]
The issue still seems to be present in 2.2.4:

http://jsbin.com/gaqewihaha/edit?html,js,output

Here is my PR: https://github.com/Semantic-Org/Semantic-UI/pull/4510

**Comment by dorsha** [comment]
@martinduparc try this one: http://jsbin.com/zitasehexi/edit?html,js,output
It works as expect... value, text and selectedItem are defined (and you can see the selected elements).

![image](https://cloud.githubusercontent.com/assets/5429033/18141796/a052dd5a-6fc3-11e6-879d-b0faf4f8651a.png)

**Comment by martinduparc** [comment]
Thanks @dorsha but this isn't the behavior I am expected. The dropdown you used is multiple and I need the action to be `select` to retain the current text.

**Comment by dorsha** [comment]
@martinduparc 
So just remove the multiple attribute:

http://jsbin.com/huyazequnu/1/edit?html,js,output

Seems to work (single select + correct values are printed):
![image](https://cloud.githubusercontent.com/assets/5429033/18166611/b42b28d2-7054-11e6-982b-d1740e25c4bd.png)

**Comment by martinduparc** [comment]
@dorsha Works well without the `select` action but doesn't when the option is set: 
http://jsbin.com/dokigupawu/edit?html,js,output

**Comment by dorsha** [comment]
Yes, because when having the `select` option, the the dropdown does not change the current text. 
 
From their documentation:
http://semantic-ui.com/modules/dropdown.html#/settings  

![image](https://cloud.githubusercontent.com/assets/5429033/18174449/46d3805a-7076-11e6-942f-301ba5ce4351.png)

It is more likely to use the `select` option when you don't want the text to be changed, like in the following dropdown:
![image](https://cloud.githubusercontent.com/assets/5429033/18174526/818c029e-7076-11e6-9b80-0e3f2562c6b3.png)

**Comment by martinduparc** [comment]
The behavior must have changed then since `$selectedItem` was working in v2.1. The documentation still states the following `onChange(value, text, $choice)` so it might be outdated?
