### ISSUE TITLE
[Message] - Compact class incompatible with icon class

### ISSUE THREAD

**Issue by dmaison** [Semantic-Org/Semantic-UI#4759]
**Steps to Reproduce**
1. Create `<div class="ui compact icon message" />`

**Expected**
The Message should do be producing an icon message that is compact

**Result**
The compact class is ignored and element is displayed as block (full width)

**Testcase**
(fork this to get started)
http://jsfiddle.net/95kzk6mr/1/

**Comment by neokio** [comment]
Confirmed ... +1

**Comment by jlukic** [comment]
Fixed in `2.2.11`

**Comment by neokio** [comment]
@jlukic Hey there ... either this wasn't fixed, or it reverted back in 2.2.12. Using the original Testcase above (http://jsfiddle.net/95kzk6mr/1/), the `ui compact icon message` still renders at 100% width.

**Comment by GammaGames** [comment]
Seems like a simple fix, though I'm sure they don't want a lot of special case css in the library because it would make it harder to maintain. I override it with the following rule for now:

```css
 .compact.icon.message {
    width: inherit;
}
```

**Comment by lubber-de** [comment]
>  Maybe Fomantic will fix it
We finally did :wink:
