### ISSUE TITLE
Clicking dropdown doesn't fire click event. (Proven on semantic-ui website)

### ISSUE THREAD

**Issue by Kjaal** [Semantic-Org/Semantic-UI#5191]
Hello, I have now tested this issue on 3 seperate computers, and have got to the conclusion that it only works on touch devices.
[Gif of problem](https://i.gyazo.com/c21b829fe01e5339a9b344ca2d8efa5e.mp4)

As you can see on the gif nothing happens when you click the item, it does not add it to the list of selected items.

Inspecting this with debug enabled, it seems the only events fired when triggered is `"Hiding dropdown"`.
I tried adding some external jQuery to trigger an event whenever this was clicked, but was unable to do so.
The events I added externally was `.click() .on('click')` and I even tried `.delegate('click')` none of which fired when clicking on the item.

The interesting thing is when clicking on these element on a touch device, everything works as intended. [As proven here](https://i.gyazo.com/b42821fe9e704cc90a8d8e447ab44e4e.mp4)

This might be a CSS issue, but I couldn't find any reasoning behind it.

**Comment by Banandrew** [comment]
Hi @Kjaal, it was fixed for `2.2.10`: #5113.

**Comment by Kjaal** [comment]
Hi @Banandrew but the problem still exists on the website and in the latest version? Looking at the current build it still shows it being in build 2.2.9 ? Where can I upgrade to the 2.2.10 ?

**Comment by Banandrew** [comment]
@Kjaal you can’t, because it wasn’t released yet.
